version: '3.8'

services:
  backend:
    build: ./backend
    container_name: wattbox-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/wattbox.db
      - UPLOAD_DIRECTORY=/app/static/uploads
      - TESSERACT_PATH=/usr/bin/tesseract
      - PRICE_PER_KWH=0.42
      - ALLOWED_DEVICE_IDS=esp1,esp2,esp3
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5174,http://localhost:3000,http://localhost:8080
    restart: unless-stopped

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wattbox-frontend-dev
    ports:
      - "5174:5173"  # Map to 5174 externally to avoid conflicts
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data: